apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr-prod
    app.kubernetes.io/component: movie-manager
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
    env: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr-prod
        app.kubernetes.io/component: movie-manager
        app.kubernetes.io/part-of: media-stack
        app.kubernetes.io/managed-by: argocd
        env: prod
    spec:
      nodeSelector:
        kubernetes.io/hostname: linux2
      securityContext:
        fsGroup: 1000
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.4.4.10685-ls318
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Paris
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 1536Mi
          startupProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /ping
              port: 7878
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 7878
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-stockage-pvc
