apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent-prod
    app.kubernetes.io/component: downloader
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-alt
      port: 8085
      targetPort: 8080
      protocol: TCP
    - name: torrent-tcp
      port: 6882
      targetPort: 6882
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-udp
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent-prod
    app.kubernetes.io/component: downloader
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - name: torrent-udp
      port: 6882
      targetPort: 6882
      protocol: UDP
