apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-stockage-pv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: media-stockage-pv
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /stockage
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - linux2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-stockage-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: media-stockage-pvc
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: media-stockage-pv
  resources:
    requests:
      storage: 5Ti
