apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/instance: jellyseerr-prod
    app.kubernetes.io/component: request-manager
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
      protocol: TCP
