name: Validate Kubernetes Manifests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Kustomize Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Validate Kustomize Build
        run: |
          kustomize build manifests/workloads/media-stack/overlays/prod
